language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - mkdir -p ~/.composer
  - echo '{"config":{"github-oauth":{"github.com":"ab9ea0a3de5574f0b337a5515a302afd25b33089"}}}' > ~/.composer/config.json
  - composer self-update
  - composer update --prefer-source --dev --no-interaction

script: 
  - vendor/bin/phpunit

after_script:
  - php vendor/bin/php-coveralls -v